# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
    # You can define as many lanes as you want
  lane :example do
    say "Funciona! Meu primeiro lane personalizado."
  end
  lane :test do
     scan(scheme: "Github Celebrities")
     slather(
       output_directory: "coverage",
       workspace: "Github Celebrities.xcworkspace",
       scheme: "Github Celebrities",
       proj: "Github Celebrities.xcodeproj",
       html: true
     )
   end
end
