//
//  GithubCelebritiesWorker.swift
//  Github Celebrities
//
//  Created by Israel on 18/02/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

final class GithubCelebritiesWorker {
    func getUsers(_ request: GithubCelebrities.Users.Request, completion: @escaping (Result<UsersCelebrities, NetworkingError>) -> Void) {
        NetworkingAPI().getUsers(request) { result in
            completion(result)
        }
    }
}
