//
//  GithubCelebritiesViewController.swift
//  Github Celebrities
//
//  Created by Israel on 18/02/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol GithubCelebritiesDisplayLogic: class {
    func displaySomething(viewModel: GithubCelebrities.Users.ViewModel)
    func displayError()
    func toggleLoading(_ bool: Bool)
}

class GithubCelebritiesViewController: UIViewController {
    
    var interactor: GithubCelebritiesBusinessLogic?
    var users: [User] = []
    private var page = 1, totalPages = 1
    var tableView: UITableView = {
        let tableView = UITableView(frame: .zero)
        tableView.translatesAutoresizingMaskIntoConstraints = false
        return tableView
    }()
    
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        setupTableView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        getUsers()
    }

    // MARK: Setup
    
    private func setup() {
        let interactor = GithubCelebritiesInteractor()
        let presenter = GithubCelebritiesPresenter()
        self.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = self
    }
    
    private func setupTableView() {
        view.addSubview(tableView)
        tableView.delegate = self
        tableView.dataSource = self
        tableView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        tableView.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        tableView.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
    }
    
    // MARK: Get Users
    
    func getUsers() {
        let request = GithubCelebrities.Users.Request()
        interactor?.getUsers(request: request)
    }
}

//MARK: - GithubCelebritiesDisplayLogic
extension GithubCelebritiesViewController: GithubCelebritiesDisplayLogic {

    func displaySomething(viewModel: GithubCelebrities.Users.ViewModel) {
        guard let usersCelebrities = viewModel.usersCelebrities?.items else { return }
        guard let totalPagesInResult = viewModel.usersCelebrities?.totalCount else { return }
        users.append(contentsOf: usersCelebrities)
        totalPages = totalPagesInResult
        DispatchQueue.main.async {
            self.tableView.reloadData()
            self.toggleLoading(false)
        }
    }

    func displayError() {
        
    }
    
    func toggleLoading(_ bool: Bool) {
    
    }
}


//MARK: - UITableViewDataSource
extension GithubCelebritiesViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return users.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = UITableViewCell(style: .subtitle, reuseIdentifier: "cellIdentifier")
        
        let user = users[indexPath.row]
        cell.textLabel?.text = user.name
        
        if let username = user.owner?.login, let countStars = user.stargazers_count {
            cell.detailTextLabel?.text = "\(username) (\(countStars) estrelas)"
        }

        if let stringUrl = user.owner?.avatarUrl, let urlImage = URL(string: stringUrl) {
            cell.imageView?.kf.indicatorType = .activity
            cell.imageView?.kf.setImage(with: urlImage, placeholder: UIImage(named: "iTunesArtwork"))
        }
        
        return cell
    }
}


//MARK: - UITableViewDelegate
extension GithubCelebritiesViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 100
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        let lastItem = users.count - 1
        if indexPath.row == lastItem {
            page+=1
            if !(page > totalPages){
                getUsers()
//                getUsers(page: page)
            }
        }
    }
}
