//
//  GithubCelebritiesModels.swift
//  Github Celebrities
//
//  Created by Israel on 18/02/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum GithubCelebrities {
    // MARK: Use cases
    
    enum Users {
        
        struct Request {
            var page: Int = 1
        }
        
        struct Response {
            var usersCelebrities: UsersCelebrities?
        }
        
        struct ViewModel {
            var usersCelebrities: UsersCelebrities?
        }
    }
}
