//
//  GithubCelebritiesWorker.swift
//  Github Celebrities
//
//  Created by Israel on 18/02/20.
//  Copyright (c) 2020 israel3D. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates and
//  edited by Israel Mesquita.
//  So you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class GithubCelebritiesWorker {
    
    func getUsers(_ request: GithubCelebrities.Users.Request, onComplete:@escaping(Result<UsersCelebrities,Error>) -> Void) {
        API.getUsers(request) { (result) in
            onComplete(result)
        }
    }
    
//    func getAPIUserData() -> Result<UsersCelebrities,Error>? {
//        
//        if let path = Bundle.main.path(forResource: "UsersCelebrities", ofType: "json") {
//            do {
//                let data = try Data(contentsOf: URL(fileURLWithPath: path), options: .alwaysMapped)
//                let decoder = JSONDecoder()
//                decoder.keyDecodingStrategy = .convertFromSnakeCase
//                if let result = try? decoder.decode(UsersCelebrities.self, from: data) {
//                    return .success(result)
//                }
//            } catch let error {
//                print("Error: \(error)")
//                return .failure(error)
//            }
//        }
//        return nil
//    }
}
